blank_issues_enabled: false
contact_links:
  - name: Nous rejoindre sur Discord, pour toutes questions ou demandes
    url: https://discord.gg/CU9KZCFQVy
    about: Veuillez ne pas ouvrir d'issue autre que pour signaler des bugs
